### PR TITLE
Keep the Github Actions updated

### PR DESCRIPTION
**Pull request by edumco**
Adds dependabot checks to the Github actions

### CODE REVIEW

**Comment by jonasbn** [comment]
Hi @edumco 

What is the difference to the `docker` package-ecosystem ?

**Comment by edumco** [comment]
The 'docker' ecosystem updates the versions of docker images like in:

```yml
FROM python:3.9.4-slim
```

The actions updates the version of Github actions used in CI like in:

```yml
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.13.0
```
After the **@** comes the version. Here you are using the checkout action in version master (it will download master and build) and spellcheck version 0.13.0 (it will download the git tag)

**Comment by jonasbn** [comment]
Hi @edumco 

Thanks for the explanation

**Review by jonasbn — APPROVED** [review]
Looks good

**Pull request merged**
