### PR TITLE
Add source_files and task_name options

### PR DESCRIPTION
**Pull request by miff2000**
This PR adds these two new settings which can be passed into the Action
* `source_files` allows a list of specific files to scan to be provided
* `task_name` allows a specific task to be executed

### CODE REVIEW

**Comment by miff2000** [comment]
Actually, if it's preferred, I could add an `extra_flags` option which would allow any arbitrary options to be passed to PySpelling instead?

**Comment by jonasbn** [comment]
Hi @miff2000 

I will have a loot at the PR and will get back to you. I plan to review it tomorrow.

**Review by jonasbn — APPROVED** [review]
This looks good, I might apply some additional changes, primarily on the documentation parts - I hope this is okay.

Thank you for you contribution

**Comment by miff2000** [comment]
> This looks good, I might apply some additional changes, primarily on the documentation parts - I hope this is okay.
> 
> Thank you for you contribution

I've just added a merge commit to add your updates in :) Thanks for the quick turnaround!

**Review by jonasbn — APPROVED** [review]
This looks good

**Comment by jonasbn** [comment]
This is included in release 0.10.0, thank you for your contribution

**Comment by edumco** [comment]
This PR closes #33

**Pull request merged**
